// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chats/clients": {
            "get": {
                "description": "client chat websocket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "client chat websocket",
                "responses": {}
            }
        },
        "/chats/supports": {
            "get": {
                "description": "client chat websocket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Websocket"
                ],
                "summary": "client chat websocket",
                "responses": {}
            }
        },
        "/conversations/active": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "get user active conversation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "GetActiveConversation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Conversation"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health-check": {
            "get": {
                "description": "health check chat service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "health check chat service",
                "responses": {
                    "200": {
                        "description": "everything is good",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.Conversation": {
            "type": "object",
            "properties": {
                "assigned_support_id": {
                    "$ref": "#/definitions/types.ID"
                },
                "client_user_id": {
                    "$ref": "#/definitions/types.ID"
                },
                "closed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "$ref": "#/definitions/types.ID"
                },
                "last_message_sender_id": {
                    "$ref": "#/definitions/types.ID"
                },
                "last_message_snippet": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/service.ConversationStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.ConversationStatus": {
            "type": "string",
            "enum": [
                "new",
                "open",
                "closed",
                "bot_handling"
            ],
            "x-enum-varnames": [
                "ConversationStatusNew",
                "ConversationStatusOpen",
                "ConversationStatusClosed",
                "ConversationStatusBotHandling"
            ]
        },
        "types.ID": {
            "type": "string",
            "enum": [
                "01J00000000000000000000BOT"
            ],
            "x-enum-varnames": [
                "BotUserID"
            ]
        }
    },
    "securityDefinitions": {
        "JWT": {
            "description": "JWT security accessToken. Please add it in the format \"Bearer {AccessToken}\" to authorize your requests.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
