// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: storage/proto/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_storage_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_storage_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_storage_proto_storage_proto protoreflect.FileDescriptor

const file_storage_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bstorage/proto/storage.proto\x12\astorage\"(\n" +
	"\rGetURLRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\"\n" +
	"\x0eGetURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2K\n" +
	"\x0eStorageService\x129\n" +
	"\x06GetURL\x12\x16.storage.GetURLRequest\x1a\x17.storage.GetURLResponseB#Z!protobuf/storage/golang/storagepbb\x06proto3"

var (
	file_storage_proto_storage_proto_rawDescOnce sync.Once
	file_storage_proto_storage_proto_rawDescData []byte
)

func file_storage_proto_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_storage_proto_rawDesc), len(file_storage_proto_storage_proto_rawDesc)))
	})
	return file_storage_proto_storage_proto_rawDescData
}

var file_storage_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_storage_proto_storage_proto_goTypes = []any{
	(*GetURLRequest)(nil),  // 0: storage.GetURLRequest
	(*GetURLResponse)(nil), // 1: storage.GetURLResponse
}
var file_storage_proto_storage_proto_depIdxs = []int32{
	0, // 0: storage.StorageService.GetURL:input_type -> storage.GetURLRequest
	1, // 1: storage.StorageService.GetURL:output_type -> storage.GetURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_proto_storage_proto_init() }
func file_storage_proto_storage_proto_init() {
	if File_storage_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_storage_proto_rawDesc), len(file_storage_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_storage_proto_msgTypes,
	}.Build()
	File_storage_proto_storage_proto = out.File
	file_storage_proto_storage_proto_goTypes = nil
	file_storage_proto_storage_proto_depIdxs = nil
}
