// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: storage/proto/storage_internal.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_storage_proto_storage_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_storage_internal_proto_rawDescGZIP(), []int{0}
}

func (x *GetLinkRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_storage_proto_storage_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_storage_internal_proto_rawDescGZIP(), []int{1}
}

func (x *GetLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_storage_proto_storage_internal_proto protoreflect.FileDescriptor

const file_storage_proto_storage_internal_proto_rawDesc = "" +
	"\n" +
	"$storage/proto/storage_internal.proto\x12\astorage\")\n" +
	"\x0eGetLinkRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"#\n" +
	"\x0fGetLinkResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2V\n" +
	"\x16StorageInternalService\x12<\n" +
	"\aGetLink\x12\x17.storage.GetLinkRequest\x1a\x18.storage.GetLinkResponseB#Z!protobuf/storage/golang/storagepbb\x06proto3"

var (
	file_storage_proto_storage_internal_proto_rawDescOnce sync.Once
	file_storage_proto_storage_internal_proto_rawDescData []byte
)

func file_storage_proto_storage_internal_proto_rawDescGZIP() []byte {
	file_storage_proto_storage_internal_proto_rawDescOnce.Do(func() {
		file_storage_proto_storage_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_storage_internal_proto_rawDesc), len(file_storage_proto_storage_internal_proto_rawDesc)))
	})
	return file_storage_proto_storage_internal_proto_rawDescData
}

var file_storage_proto_storage_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_storage_proto_storage_internal_proto_goTypes = []any{
	(*GetLinkRequest)(nil),  // 0: storage.GetLinkRequest
	(*GetLinkResponse)(nil), // 1: storage.GetLinkResponse
}
var file_storage_proto_storage_internal_proto_depIdxs = []int32{
	0, // 0: storage.StorageInternalService.GetLink:input_type -> storage.GetLinkRequest
	1, // 1: storage.StorageInternalService.GetLink:output_type -> storage.GetLinkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_proto_storage_internal_proto_init() }
func file_storage_proto_storage_internal_proto_init() {
	if File_storage_proto_storage_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_storage_internal_proto_rawDesc), len(file_storage_proto_storage_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_storage_internal_proto_goTypes,
		DependencyIndexes: file_storage_proto_storage_internal_proto_depIdxs,
		MessageInfos:      file_storage_proto_storage_internal_proto_msgTypes,
	}.Build()
	File_storage_proto_storage_internal_proto = out.File
	file_storage_proto_storage_internal_proto_goTypes = nil
	file_storage_proto_storage_internal_proto_depIdxs = nil
}
