// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: storage/proto/storage_internal.proto

package storagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageInternalService_GetLink_FullMethodName = "/storage.StorageInternalService/GetLink"
)

// StorageInternalServiceClient is the client API for StorageInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageInternalServiceClient interface {
	GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*GetLinkResponse, error)
}

type storageInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageInternalServiceClient(cc grpc.ClientConnInterface) StorageInternalServiceClient {
	return &storageInternalServiceClient{cc}
}

func (c *storageInternalServiceClient) GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*GetLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLinkResponse)
	err := c.cc.Invoke(ctx, StorageInternalService_GetLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageInternalServiceServer is the server API for StorageInternalService service.
// All implementations must embed UnimplementedStorageInternalServiceServer
// for forward compatibility.
type StorageInternalServiceServer interface {
	GetLink(context.Context, *GetLinkRequest) (*GetLinkResponse, error)
	mustEmbedUnimplementedStorageInternalServiceServer()
}

// UnimplementedStorageInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageInternalServiceServer struct{}

func (UnimplementedStorageInternalServiceServer) GetLink(context.Context, *GetLinkRequest) (*GetLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedStorageInternalServiceServer) mustEmbedUnimplementedStorageInternalServiceServer() {
}
func (UnimplementedStorageInternalServiceServer) testEmbeddedByValue() {}

// UnsafeStorageInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageInternalServiceServer will
// result in compilation errors.
type UnsafeStorageInternalServiceServer interface {
	mustEmbedUnimplementedStorageInternalServiceServer()
}

func RegisterStorageInternalServiceServer(s grpc.ServiceRegistrar, srv StorageInternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedStorageInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageInternalService_ServiceDesc, srv)
}

func _StorageInternalService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageInternalServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageInternalService_GetLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageInternalServiceServer).GetLink(ctx, req.(*GetLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageInternalService_ServiceDesc is the grpc.ServiceDesc for StorageInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageInternalService",
	HandlerType: (*StorageInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLink",
			Handler:    _StorageInternalService_GetLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/proto/storage_internal.proto",
}
