// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: manager/proto/auth.proto

package authpb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_manager_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublicKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_manager_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresIn  int32                  `protobuf:"varint,3,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`
	RefreshExpiresIn int32                  `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_manager_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetAccessExpiresIn() int32 {
	if x != nil {
		return x.AccessExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetRefreshExpiresIn() int32 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

type TokenVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenVerifyRequest) Reset() {
	*x = TokenVerifyRequest{}
	mi := &file_manager_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyRequest) ProtoMessage() {}

func (x *TokenVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyRequest.ProtoReflect.Descriptor instead.
func (*TokenVerifyRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *TokenVerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenVerifyResponse) Reset() {
	*x = TokenVerifyResponse{}
	mi := &file_manager_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyResponse) ProtoMessage() {}

func (x *TokenVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyResponse.ProtoReflect.Descriptor instead.
func (*TokenVerifyResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenVerifyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenVerifyResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *TokenVerifyResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type TokenRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRefreshRequest) Reset() {
	*x = TokenRefreshRequest{}
	mi := &file_manager_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefreshRequest) ProtoMessage() {}

func (x *TokenRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefreshRequest.ProtoReflect.Descriptor instead.
func (*TokenRefreshRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *TokenRefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenRefreshResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresIn  int32                  `protobuf:"varint,3,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`
	RefreshExpiresIn int32                  `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenRefreshResponse) Reset() {
	*x = TokenRefreshResponse{}
	mi := &file_manager_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefreshResponse) ProtoMessage() {}

func (x *TokenRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefreshResponse.ProtoReflect.Descriptor instead.
func (*TokenRefreshResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *TokenRefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenRefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenRefreshResponse) GetAccessExpiresIn() int32 {
	if x != nil {
		return x.AccessExpiresIn
	}
	return 0
}

func (x *TokenRefreshResponse) GetRefreshExpiresIn() int32 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

var File_manager_proto_auth_proto protoreflect.FileDescriptor

const file_manager_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x18manager/proto/auth.proto\x12\amanager\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\x14GetPublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb1\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12*\n" +
	"\x11access_expires_in\x18\x03 \x01(\x05R\x0faccessExpiresIn\x12,\n" +
	"\x12refresh_expires_in\x18\x04 \x01(\x05R\x10refreshExpiresIn\"*\n" +
	"\x12TokenVerifyRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"c\n" +
	"\x13TokenVerifyResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\":\n" +
	"\x13TokenRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xb8\x01\n" +
	"\x14TokenRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12*\n" +
	"\x11access_expires_in\x18\x03 \x01(\x05R\x0faccessExpiresIn\x12,\n" +
	"\x12refresh_expires_in\x18\x04 \x01(\x05R\x10refreshExpiresIn2\xa3\x02\n" +
	"\vAuthService\x12E\n" +
	"\fGetPublicKey\x12\x16.google.protobuf.Empty\x1a\x1d.manager.GetPublicKeyResponse\x126\n" +
	"\x05Login\x12\x15.manager.LoginRequest\x1a\x16.manager.LoginResponse\x12H\n" +
	"\vTokenVerify\x12\x1b.manager.TokenVerifyRequest\x1a\x1c.manager.TokenVerifyResponse\x12K\n" +
	"\fTokenRefresh\x12\x1c.manager.TokenRefreshRequest\x1a\x1d.manager.TokenRefreshResponseB Z\x1eprotobuf/manager/golang/authpbb\x06proto3"

var (
	file_manager_proto_auth_proto_rawDescOnce sync.Once
	file_manager_proto_auth_proto_rawDescData []byte
)

func file_manager_proto_auth_proto_rawDescGZIP() []byte {
	file_manager_proto_auth_proto_rawDescOnce.Do(func() {
		file_manager_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_proto_auth_proto_rawDesc), len(file_manager_proto_auth_proto_rawDesc)))
	})
	return file_manager_proto_auth_proto_rawDescData
}

var file_manager_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_manager_proto_auth_proto_goTypes = []any{
	(*GetPublicKeyResponse)(nil), // 0: manager.GetPublicKeyResponse
	(*LoginRequest)(nil),         // 1: manager.LoginRequest
	(*LoginResponse)(nil),        // 2: manager.LoginResponse
	(*TokenVerifyRequest)(nil),   // 3: manager.TokenVerifyRequest
	(*TokenVerifyResponse)(nil),  // 4: manager.TokenVerifyResponse
	(*TokenRefreshRequest)(nil),  // 5: manager.TokenRefreshRequest
	(*TokenRefreshResponse)(nil), // 6: manager.TokenRefreshResponse
	(*empty.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_manager_proto_auth_proto_depIdxs = []int32{
	7, // 0: manager.AuthService.GetPublicKey:input_type -> google.protobuf.Empty
	1, // 1: manager.AuthService.Login:input_type -> manager.LoginRequest
	3, // 2: manager.AuthService.TokenVerify:input_type -> manager.TokenVerifyRequest
	5, // 3: manager.AuthService.TokenRefresh:input_type -> manager.TokenRefreshRequest
	0, // 4: manager.AuthService.GetPublicKey:output_type -> manager.GetPublicKeyResponse
	2, // 5: manager.AuthService.Login:output_type -> manager.LoginResponse
	4, // 6: manager.AuthService.TokenVerify:output_type -> manager.TokenVerifyResponse
	6, // 7: manager.AuthService.TokenRefresh:output_type -> manager.TokenRefreshResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_manager_proto_auth_proto_init() }
func file_manager_proto_auth_proto_init() {
	if File_manager_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_proto_auth_proto_rawDesc), len(file_manager_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_proto_auth_proto_goTypes,
		DependencyIndexes: file_manager_proto_auth_proto_depIdxs,
		MessageInfos:      file_manager_proto_auth_proto_msgTypes,
	}.Build()
	File_manager_proto_auth_proto = out.File
	file_manager_proto_auth_proto_goTypes = nil
	file_manager_proto_auth_proto_depIdxs = nil
}
