// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: example/proto/example.proto

package examplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCommentByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentByIDRequest) Reset() {
	*x = GetCommentByIDRequest{}
	mi := &file_example_proto_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentByIDRequest) ProtoMessage() {}

func (x *GetCommentByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCommentByIDRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *GetCommentByIDRequest) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentResponse) Reset() {
	*x = GetCommentResponse{}
	mi := &file_example_proto_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentResponse) ProtoMessage() {}

func (x *GetCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentResponse.ProtoReflect.Descriptor instead.
func (*GetCommentResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *GetCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *GetCommentResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_example_proto_example_proto protoreflect.FileDescriptor

const file_example_proto_example_proto_rawDesc = "" +
	"\n" +
	"\x1bexample/proto/example.proto\x12\x05micro\"6\n" +
	"\x15GetCommentByIDRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x04R\tcommentId\"G\n" +
	"\x12GetCommentResponse\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x04R\tcommentId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body2W\n" +
	"\x0eCommentService\x12E\n" +
	"\n" +
	"GetComment\x12\x1c.micro.GetCommentByIDRequest\x1a\x19.micro.GetCommentResponseB#Z!protobuf/example/golang/examplepbb\x06proto3"

var (
	file_example_proto_example_proto_rawDescOnce sync.Once
	file_example_proto_example_proto_rawDescData []byte
)

func file_example_proto_example_proto_rawDescGZIP() []byte {
	file_example_proto_example_proto_rawDescOnce.Do(func() {
		file_example_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_example_proto_rawDesc), len(file_example_proto_example_proto_rawDesc)))
	})
	return file_example_proto_example_proto_rawDescData
}

var file_example_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_proto_example_proto_goTypes = []any{
	(*GetCommentByIDRequest)(nil), // 0: micro.GetCommentByIDRequest
	(*GetCommentResponse)(nil),    // 1: micro.GetCommentResponse
}
var file_example_proto_example_proto_depIdxs = []int32{
	0, // 0: micro.CommentService.GetComment:input_type -> micro.GetCommentByIDRequest
	1, // 1: micro.CommentService.GetComment:output_type -> micro.GetCommentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_example_proto_init() }
func file_example_proto_example_proto_init() {
	if File_example_proto_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_example_proto_rawDesc), len(file_example_proto_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_example_proto_goTypes,
		DependencyIndexes: file_example_proto_example_proto_depIdxs,
		MessageInfos:      file_example_proto_example_proto_msgTypes,
	}.Build()
	File_example_proto_example_proto = out.File
	file_example_proto_example_proto_goTypes = nil
	file_example_proto_example_proto_depIdxs = nil
}
