// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: manager/proto/user.proto

package userpb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED  Role = 0
	Role_ROLE_SUPERUSER    Role = 1
	Role_ROLE_SUPPORT      Role = 2
	Role_ROLE_STORY        Role = 3
	Role_ROLE_FILE         Role = 4
	Role_ROLE_NOTIFICATION Role = 5
	Role_ROLE_CLIENT       Role = 6
	Role_ROLE_GUEST        Role = 7
	Role_ROLE_BOT          Role = 8
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_SUPERUSER",
		2: "ROLE_SUPPORT",
		3: "ROLE_STORY",
		4: "ROLE_FILE",
		5: "ROLE_NOTIFICATION",
		6: "ROLE_CLIENT",
		7: "ROLE_GUEST",
		8: "ROLE_BOT",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED":  0,
		"ROLE_SUPERUSER":    1,
		"ROLE_SUPPORT":      2,
		"ROLE_STORY":        3,
		"ROLE_FILE":         4,
		"ROLE_NOTIFICATION": 5,
		"ROLE_CLIENT":       6,
		"ROLE_GUEST":        7,
		"ROLE_BOT":          8,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_manager_proto_user_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_manager_proto_user_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{0}
}

type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASC         SortDirection = 1
	SortDirection_SORT_DIRECTION_DESC        SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASC",
		2: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASC":         1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_manager_proto_user_proto_enumTypes[1].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_manager_proto_user_proto_enumTypes[1]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{1}
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Roles         []Role                 `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=manager.Role" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_manager_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Roles         []Role                 `protobuf:"varint,7,rep,packed,name=roles,proto3,enum=manager.Role" json:"roles,omitempty"`
	LastOnlineAt  *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=last_online_at,json=lastOnlineAt,proto3" json:"last_online_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_manager_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetLastOnlineAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastOnlineAt
	}
	return nil
}

type UserDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailRequest) Reset() {
	*x = UserDetailRequest{}
	mi := &file_manager_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailRequest) ProtoMessage() {}

func (x *UserDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailRequest.ProtoReflect.Descriptor instead.
func (*UserDetailRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserDetailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_manager_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDeleteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserUpdateFromSuperUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Roles         []Role                 `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=manager.Role" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateFromSuperUserRequest) Reset() {
	*x = UserUpdateFromSuperUserRequest{}
	mi := &file_manager_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateFromSuperUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateFromSuperUserRequest) ProtoMessage() {}

func (x *UserUpdateFromSuperUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateFromSuperUserRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateFromSuperUserRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserUpdateFromSuperUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserUpdateFromSuperUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpdateFromSuperUserRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserUpdateFromSuperUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateFromSuperUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserUpdateFromSuperUserRequest) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserUpdateFromOwnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateFromOwnRequest) Reset() {
	*x = UserUpdateFromOwnRequest{}
	mi := &file_manager_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateFromOwnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateFromOwnRequest) ProtoMessage() {}

func (x *UserUpdateFromOwnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateFromOwnRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateFromOwnRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserUpdateFromOwnRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpdateFromOwnRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserUpdateFromOwnRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateFromOwnRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   uint64                 `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortDirection SortDirection          `protobuf:"varint,3,opt,name=sort_direction,json=sortDirection,proto3,enum=manager.SortDirection" json:"sort_direction,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Roles         []Role                 `protobuf:"varint,5,rep,packed,name=roles,proto3,enum=manager.Role" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_manager_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserListRequest) GetCurrentPage() uint64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *UserListRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserListRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

func (x *UserListRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserListRequest) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   uint64                 `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalNumber   uint64                 `protobuf:"varint,3,opt,name=total_number,json=totalNumber,proto3" json:"total_number,omitempty"`
	TotalPage     uint64                 `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	Users         []*User                `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_manager_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserListResponse) GetCurrentPage() uint64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *UserListResponse) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserListResponse) GetTotalNumber() uint64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *UserListResponse) GetTotalPage() uint64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *UserListResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserChangePasswordRequest) Reset() {
	*x = UserChangePasswordRequest{}
	mi := &file_manager_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChangePasswordRequest) ProtoMessage() {}

func (x *UserChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*UserChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UserChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

var File_manager_proto_user_proto protoreflect.FileDescriptor

const file_manager_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x18manager/proto/user.proto\x12\amanager\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc5\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12#\n" +
	"\x05roles\x18\x06 \x03(\x0e2\r.manager.RoleR\x05roles\"\x86\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12#\n" +
	"\x05roles\x18\a \x03(\x0e2\r.manager.RoleR\x05roles\x12@\n" +
	"\x0elast_online_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastOnlineAt\",\n" +
	"\x11UserDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x11UserDeleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xcf\x01\n" +
	"\x1eUserUpdateFromSuperUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12#\n" +
	"\x05roles\x18\x06 \x03(\x0e2\r.manager.RoleR\x05roles\"\x8b\x01\n" +
	"\x18UserUpdateFromOwnRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\"\xd1\x01\n" +
	"\x0fUserListRequest\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x04R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12=\n" +
	"\x0esort_direction\x18\x03 \x01(\x0e2\x16.manager.SortDirectionR\rsortDirection\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12#\n" +
	"\x05roles\x18\x05 \x03(\x0e2\r.manager.RoleR\x05roles\"\xb9\x01\n" +
	"\x10UserListResponse\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x04R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12!\n" +
	"\ftotal_number\x18\x03 \x01(\x04R\vtotalNumber\x12\x1d\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x04R\ttotalPage\x12#\n" +
	"\x05users\x18\x05 \x03(\v2\r.manager.UserR\x05users\"a\n" +
	"\x19UserChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword*\xa7\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eROLE_SUPERUSER\x10\x01\x12\x10\n" +
	"\fROLE_SUPPORT\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_STORY\x10\x03\x12\r\n" +
	"\tROLE_FILE\x10\x04\x12\x15\n" +
	"\x11ROLE_NOTIFICATION\x10\x05\x12\x0f\n" +
	"\vROLE_CLIENT\x10\x06\x12\x0e\n" +
	"\n" +
	"ROLE_GUEST\x10\a\x12\f\n" +
	"\bROLE_BOT\x10\b*`\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x022\xa4\x04\n" +
	"\vUserService\x127\n" +
	"\n" +
	"CreateUser\x12\x1a.manager.CreateUserRequest\x1a\r.manager.User\x127\n" +
	"\n" +
	"UserDetail\x12\x1a.manager.UserDetailRequest\x1a\r.manager.User\x12@\n" +
	"\n" +
	"UserDelete\x12\x1a.manager.UserDeleteRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x17UserUpdateFromSuperuser\x12'.manager.UserUpdateFromSuperUserRequest\x1a\r.manager.User\x12E\n" +
	"\x11UserUpdateFromOwn\x12!.manager.UserUpdateFromOwnRequest\x1a\r.manager.User\x12?\n" +
	"\bUserList\x12\x18.manager.UserListRequest\x1a\x19.manager.UserListResponse\x124\n" +
	"\vUserProfile\x12\x16.google.protobuf.Empty\x1a\r.manager.User\x12P\n" +
	"\x12UserChangePassword\x12\".manager.UserChangePasswordRequest\x1a\x16.google.protobuf.EmptyB Z\x1eprotobuf/manager/golang/userpbb\x06proto3"

var (
	file_manager_proto_user_proto_rawDescOnce sync.Once
	file_manager_proto_user_proto_rawDescData []byte
)

func file_manager_proto_user_proto_rawDescGZIP() []byte {
	file_manager_proto_user_proto_rawDescOnce.Do(func() {
		file_manager_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_proto_user_proto_rawDesc), len(file_manager_proto_user_proto_rawDesc)))
	})
	return file_manager_proto_user_proto_rawDescData
}

var file_manager_proto_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_manager_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_manager_proto_user_proto_goTypes = []any{
	(Role)(0),                              // 0: manager.Role
	(SortDirection)(0),                     // 1: manager.SortDirection
	(*CreateUserRequest)(nil),              // 2: manager.CreateUserRequest
	(*User)(nil),                           // 3: manager.User
	(*UserDetailRequest)(nil),              // 4: manager.UserDetailRequest
	(*UserDeleteRequest)(nil),              // 5: manager.UserDeleteRequest
	(*UserUpdateFromSuperUserRequest)(nil), // 6: manager.UserUpdateFromSuperUserRequest
	(*UserUpdateFromOwnRequest)(nil),       // 7: manager.UserUpdateFromOwnRequest
	(*UserListRequest)(nil),                // 8: manager.UserListRequest
	(*UserListResponse)(nil),               // 9: manager.UserListResponse
	(*UserChangePasswordRequest)(nil),      // 10: manager.UserChangePasswordRequest
	(*timestamp.Timestamp)(nil),            // 11: google.protobuf.Timestamp
	(*empty.Empty)(nil),                    // 12: google.protobuf.Empty
}
var file_manager_proto_user_proto_depIdxs = []int32{
	0,  // 0: manager.CreateUserRequest.roles:type_name -> manager.Role
	0,  // 1: manager.User.roles:type_name -> manager.Role
	11, // 2: manager.User.last_online_at:type_name -> google.protobuf.Timestamp
	0,  // 3: manager.UserUpdateFromSuperUserRequest.roles:type_name -> manager.Role
	1,  // 4: manager.UserListRequest.sort_direction:type_name -> manager.SortDirection
	0,  // 5: manager.UserListRequest.roles:type_name -> manager.Role
	3,  // 6: manager.UserListResponse.users:type_name -> manager.User
	2,  // 7: manager.UserService.CreateUser:input_type -> manager.CreateUserRequest
	4,  // 8: manager.UserService.UserDetail:input_type -> manager.UserDetailRequest
	5,  // 9: manager.UserService.UserDelete:input_type -> manager.UserDeleteRequest
	6,  // 10: manager.UserService.UserUpdateFromSuperuser:input_type -> manager.UserUpdateFromSuperUserRequest
	7,  // 11: manager.UserService.UserUpdateFromOwn:input_type -> manager.UserUpdateFromOwnRequest
	8,  // 12: manager.UserService.UserList:input_type -> manager.UserListRequest
	12, // 13: manager.UserService.UserProfile:input_type -> google.protobuf.Empty
	10, // 14: manager.UserService.UserChangePassword:input_type -> manager.UserChangePasswordRequest
	3,  // 15: manager.UserService.CreateUser:output_type -> manager.User
	3,  // 16: manager.UserService.UserDetail:output_type -> manager.User
	12, // 17: manager.UserService.UserDelete:output_type -> google.protobuf.Empty
	3,  // 18: manager.UserService.UserUpdateFromSuperuser:output_type -> manager.User
	3,  // 19: manager.UserService.UserUpdateFromOwn:output_type -> manager.User
	9,  // 20: manager.UserService.UserList:output_type -> manager.UserListResponse
	3,  // 21: manager.UserService.UserProfile:output_type -> manager.User
	12, // 22: manager.UserService.UserChangePassword:output_type -> google.protobuf.Empty
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_manager_proto_user_proto_init() }
func file_manager_proto_user_proto_init() {
	if File_manager_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_proto_user_proto_rawDesc), len(file_manager_proto_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_proto_user_proto_goTypes,
		DependencyIndexes: file_manager_proto_user_proto_depIdxs,
		EnumInfos:         file_manager_proto_user_proto_enumTypes,
		MessageInfos:      file_manager_proto_user_proto_msgTypes,
	}.Build()
	File_manager_proto_user_proto = out.File
	file_manager_proto_user_proto_goTypes = nil
	file_manager_proto_user_proto_depIdxs = nil
}
