// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: chat/proto/conversation.proto

package conversationpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED  Status = 0
	Status_STATUS_NEW          Status = 1
	Status_STATUS_OPEN         Status = 2
	Status_STATUS_CLOSED       Status = 3
	Status_STATUS_BOT_HANDLING Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_NEW",
		2: "STATUS_OPEN",
		3: "STATUS_CLOSED",
		4: "STATUS_BOT_HANDLING",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"STATUS_NEW":          1,
		"STATUS_OPEN":         2,
		"STATUS_CLOSED":       3,
		"STATUS_BOT_HANDLING": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_conversation_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_chat_proto_conversation_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{0}
}

type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASC         SortDirection = 1
	SortDirection_SORT_DIRECTION_DESC        SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASC",
		2: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASC":         1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_conversation_proto_enumTypes[1].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_chat_proto_conversation_proto_enumTypes[1]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_TYPE_UNSPECIFIED MessageType = 0
	MessageType_TYPE_TEXT        MessageType = 1
	MessageType_TYPE_MEDIA       MessageType = 2
	MessageType_TYPE_SYSTEM      MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_TEXT",
		2: "TYPE_MEDIA",
		3: "TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_TEXT":        1,
		"TYPE_MEDIA":       2,
		"TYPE_SYSTEM":      3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_conversation_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_chat_proto_conversation_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{2}
}

type Conversation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientUserId        string                 `protobuf:"bytes,2,opt,name=client_user_id,json=clientUserId,proto3" json:"client_user_id,omitempty"`
	AssignedSupportId   string                 `protobuf:"bytes,3,opt,name=assigned_support_id,json=assignedSupportId,proto3" json:"assigned_support_id,omitempty"`
	Status              Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=chat.Status" json:"status,omitempty"`
	LastMessageSnippet  string                 `protobuf:"bytes,5,opt,name=last_message_snippet,json=lastMessageSnippet,proto3" json:"last_message_snippet,omitempty"`
	LastMessageSenderId string                 `protobuf:"bytes,6,opt,name=last_message_sender_id,json=lastMessageSenderId,proto3" json:"last_message_sender_id,omitempty"`
	CreatedAt           *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClosedAt            *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_chat_proto_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetClientUserId() string {
	if x != nil {
		return x.ClientUserId
	}
	return ""
}

func (x *Conversation) GetAssignedSupportId() string {
	if x != nil {
		return x.AssignedSupportId
	}
	return ""
}

func (x *Conversation) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Conversation) GetLastMessageSnippet() string {
	if x != nil {
		return x.LastMessageSnippet
	}
	return ""
}

func (x *Conversation) GetLastMessageSenderId() string {
	if x != nil {
		return x.LastMessageSenderId
	}
	return ""
}

func (x *Conversation) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Conversation) GetClosedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

type ConversationListRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage       uint64                 `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize          uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortDirection     SortDirection          `protobuf:"varint,3,opt,name=sort_direction,json=sortDirection,proto3,enum=chat.SortDirection" json:"sort_direction,omitempty"`
	AssignedSupportId string                 `protobuf:"bytes,4,opt,name=assigned_support_id,json=assignedSupportId,proto3" json:"assigned_support_id,omitempty"`
	Statuses          []Status               `protobuf:"varint,5,rep,packed,name=statuses,proto3,enum=chat.Status" json:"statuses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationListRequest) Reset() {
	*x = ConversationListRequest{}
	mi := &file_chat_proto_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationListRequest) ProtoMessage() {}

func (x *ConversationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationListRequest.ProtoReflect.Descriptor instead.
func (*ConversationListRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationListRequest) GetCurrentPage() uint64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ConversationListRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ConversationListRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

func (x *ConversationListRequest) GetAssignedSupportId() string {
	if x != nil {
		return x.AssignedSupportId
	}
	return ""
}

func (x *ConversationListRequest) GetStatuses() []Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ConversationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   uint64                 `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalNumber   uint64                 `protobuf:"varint,3,opt,name=total_number,json=totalNumber,proto3" json:"total_number,omitempty"`
	TotalPage     uint64                 `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	Conversations []*Conversation        `protobuf:"bytes,5,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationListResponse) Reset() {
	*x = ConversationListResponse{}
	mi := &file_chat_proto_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationListResponse) ProtoMessage() {}

func (x *ConversationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationListResponse.ProtoReflect.Descriptor instead.
func (*ConversationListResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationListResponse) GetCurrentPage() uint64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ConversationListResponse) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ConversationListResponse) GetTotalNumber() uint64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *ConversationListResponse) GetTotalPage() uint64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *ConversationListResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type ChatHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Cursor         string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatHistoryRequest) Reset() {
	*x = ChatHistoryRequest{}
	mi := &file_chat_proto_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryRequest) ProtoMessage() {}

func (x *ChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*ChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *ChatHistoryRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatHistoryRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Message struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId     string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId           string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MessageType        MessageType            `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=chat.MessageType" json:"message_type,omitempty"`
	Content            string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RepliedToMessageId string                 `protobuf:"bytes,7,opt,name=replied_to_message_id,json=repliedToMessageId,proto3" json:"replied_to_message_id,omitempty"`
	CreatedAt          *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt             *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_proto_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_TYPE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetRepliedToMessageId() string {
	if x != nil {
		return x.RepliedToMessageId
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetReadAt() *timestamp.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

type ChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Message             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryResponse) Reset() {
	*x = ChatHistoryResponse{}
	mi := &file_chat_proto_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryResponse) ProtoMessage() {}

func (x *ChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*ChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *ChatHistoryResponse) GetResults() []*Message {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ChatHistoryResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ChatHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type OpenConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpenConversationRequest) Reset() {
	*x = OpenConversationRequest{}
	mi := &file_chat_proto_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenConversationRequest) ProtoMessage() {}

func (x *OpenConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenConversationRequest.ProtoReflect.Descriptor instead.
func (*OpenConversationRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *OpenConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

var File_chat_proto_conversation_proto protoreflect.FileDescriptor

const file_chat_proto_conversation_proto_rawDesc = "" +
	"\n" +
	"\x1dchat/proto/conversation.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eclient_user_id\x18\x02 \x01(\tR\fclientUserId\x12.\n" +
	"\x13assigned_support_id\x18\x03 \x01(\tR\x11assignedSupportId\x12$\n" +
	"\x06status\x18\x04 \x01(\x0e2\f.chat.StatusR\x06status\x120\n" +
	"\x14last_message_snippet\x18\x05 \x01(\tR\x12lastMessageSnippet\x123\n" +
	"\x16last_message_sender_id\x18\x06 \x01(\tR\x13lastMessageSenderId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tclosed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\"\xef\x01\n" +
	"\x17ConversationListRequest\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x04R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12:\n" +
	"\x0esort_direction\x18\x03 \x01(\x0e2\x13.chat.SortDirectionR\rsortDirection\x12.\n" +
	"\x13assigned_support_id\x18\x04 \x01(\tR\x11assignedSupportId\x12(\n" +
	"\bstatuses\x18\x05 \x03(\x0e2\f.chat.StatusR\bstatuses\"\xd6\x01\n" +
	"\x18ConversationListResponse\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x04R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\x12!\n" +
	"\ftotal_number\x18\x03 \x01(\x04R\vtotalNumber\x12\x1d\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x04R\ttotalPage\x128\n" +
	"\rconversations\x18\x05 \x03(\v2\x12.chat.ConversationR\rconversations\"k\n" +
	"\x12ChatHistoryRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc8\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x124\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x11.chat.MessageTypeR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x127\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1b.chat.Message.MetadataEntryR\bmetadata\x121\n" +
	"\x15replied_to_message_id\x18\a \x01(\tR\x12repliedToMessageId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\aread_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x13ChatHistoryResponse\x12'\n" +
	"\aresults\x18\x01 \x03(\v2\r.chat.MessageR\aresults\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"B\n" +
	"\x17OpenConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId*m\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATUS_NEW\x10\x01\x12\x0f\n" +
	"\vSTATUS_OPEN\x10\x02\x12\x11\n" +
	"\rSTATUS_CLOSED\x10\x03\x12\x17\n" +
	"\x13STATUS_BOT_HANDLING\x10\x04*`\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x02*S\n" +
	"\vMessageType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_TEXT\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_MEDIA\x10\x02\x12\x0f\n" +
	"\vTYPE_SYSTEM\x10\x032\xcc\x02\n" +
	"\x13ConversationService\x12T\n" +
	"\x13ConversationNewList\x12\x1d.chat.ConversationListRequest\x1a\x1e.chat.ConversationListResponse\x12T\n" +
	"\x13ConversationOwnList\x12\x1d.chat.ConversationListRequest\x1a\x1e.chat.ConversationListResponse\x12B\n" +
	"\vChatHistory\x12\x18.chat.ChatHistoryRequest\x1a\x19.chat.ChatHistoryResponse\x12E\n" +
	"\x10OpenConversation\x12\x1d.chat.OpenConversationRequest\x1a\x12.chat.ConversationB%Z#protobuf/chat/golang/conversationpbb\x06proto3"

var (
	file_chat_proto_conversation_proto_rawDescOnce sync.Once
	file_chat_proto_conversation_proto_rawDescData []byte
)

func file_chat_proto_conversation_proto_rawDescGZIP() []byte {
	file_chat_proto_conversation_proto_rawDescOnce.Do(func() {
		file_chat_proto_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_conversation_proto_rawDesc), len(file_chat_proto_conversation_proto_rawDesc)))
	})
	return file_chat_proto_conversation_proto_rawDescData
}

var file_chat_proto_conversation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_chat_proto_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chat_proto_conversation_proto_goTypes = []any{
	(Status)(0),                      // 0: chat.Status
	(SortDirection)(0),               // 1: chat.SortDirection
	(MessageType)(0),                 // 2: chat.MessageType
	(*Conversation)(nil),             // 3: chat.Conversation
	(*ConversationListRequest)(nil),  // 4: chat.ConversationListRequest
	(*ConversationListResponse)(nil), // 5: chat.ConversationListResponse
	(*ChatHistoryRequest)(nil),       // 6: chat.ChatHistoryRequest
	(*Message)(nil),                  // 7: chat.Message
	(*ChatHistoryResponse)(nil),      // 8: chat.ChatHistoryResponse
	(*OpenConversationRequest)(nil),  // 9: chat.OpenConversationRequest
	nil,                              // 10: chat.Message.MetadataEntry
	(*timestamp.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_chat_proto_conversation_proto_depIdxs = []int32{
	0,  // 0: chat.Conversation.status:type_name -> chat.Status
	11, // 1: chat.Conversation.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: chat.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	11, // 3: chat.Conversation.closed_at:type_name -> google.protobuf.Timestamp
	1,  // 4: chat.ConversationListRequest.sort_direction:type_name -> chat.SortDirection
	0,  // 5: chat.ConversationListRequest.statuses:type_name -> chat.Status
	3,  // 6: chat.ConversationListResponse.conversations:type_name -> chat.Conversation
	2,  // 7: chat.Message.message_type:type_name -> chat.MessageType
	10, // 8: chat.Message.metadata:type_name -> chat.Message.MetadataEntry
	11, // 9: chat.Message.created_at:type_name -> google.protobuf.Timestamp
	11, // 10: chat.Message.read_at:type_name -> google.protobuf.Timestamp
	7,  // 11: chat.ChatHistoryResponse.results:type_name -> chat.Message
	4,  // 12: chat.ConversationService.ConversationNewList:input_type -> chat.ConversationListRequest
	4,  // 13: chat.ConversationService.ConversationOwnList:input_type -> chat.ConversationListRequest
	6,  // 14: chat.ConversationService.ChatHistory:input_type -> chat.ChatHistoryRequest
	9,  // 15: chat.ConversationService.OpenConversation:input_type -> chat.OpenConversationRequest
	5,  // 16: chat.ConversationService.ConversationNewList:output_type -> chat.ConversationListResponse
	5,  // 17: chat.ConversationService.ConversationOwnList:output_type -> chat.ConversationListResponse
	8,  // 18: chat.ConversationService.ChatHistory:output_type -> chat.ChatHistoryResponse
	3,  // 19: chat.ConversationService.OpenConversation:output_type -> chat.Conversation
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_chat_proto_conversation_proto_init() }
func file_chat_proto_conversation_proto_init() {
	if File_chat_proto_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_conversation_proto_rawDesc), len(file_chat_proto_conversation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_conversation_proto_goTypes,
		DependencyIndexes: file_chat_proto_conversation_proto_depIdxs,
		EnumInfos:         file_chat_proto_conversation_proto_enumTypes,
		MessageInfos:      file_chat_proto_conversation_proto_msgTypes,
	}.Build()
	File_chat_proto_conversation_proto = out.File
	file_chat_proto_conversation_proto_goTypes = nil
	file_chat_proto_conversation_proto_depIdxs = nil
}
