// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: shared/err_details.proto

package errdetailspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldViolation describes a single validation error on a field.
type FieldViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`             // The field that was invalid, e.g., "password"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // The error description, e.g., "must be at least 8 characters"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_shared_err_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_shared_err_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_shared_err_details_proto_rawDescGZIP(), []int{0}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// BadRequest contains violation for multiple fields.
// Usually used with code InvalidArgument.
type BadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FieldViolations []*FieldViolation      `protobuf:"bytes,1,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BadRequest) Reset() {
	*x = BadRequest{}
	mi := &file_shared_err_details_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadRequest) ProtoMessage() {}

func (x *BadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_err_details_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadRequest.ProtoReflect.Descriptor instead.
func (*BadRequest) Descriptor() ([]byte, []int) {
	return file_shared_err_details_proto_rawDescGZIP(), []int{1}
}

func (x *BadRequest) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

// PreconditionFailure describe errors where the system is not in a state
// require for the operation's execution.
// Usually used with code FailedPrecondition.
type PreconditionFailure struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Violations    []*PreconditionFailure_Violation `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreconditionFailure) Reset() {
	*x = PreconditionFailure{}
	mi := &file_shared_err_details_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreconditionFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreconditionFailure) ProtoMessage() {}

func (x *PreconditionFailure) ProtoReflect() protoreflect.Message {
	mi := &file_shared_err_details_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreconditionFailure.ProtoReflect.Descriptor instead.
func (*PreconditionFailure) Descriptor() ([]byte, []int) {
	return file_shared_err_details_proto_rawDescGZIP(), []int{2}
}

func (x *PreconditionFailure) GetViolations() []*PreconditionFailure_Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type PreconditionFailure_Violation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreconditionFailure_Violation) Reset() {
	*x = PreconditionFailure_Violation{}
	mi := &file_shared_err_details_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreconditionFailure_Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreconditionFailure_Violation) ProtoMessage() {}

func (x *PreconditionFailure_Violation) ProtoReflect() protoreflect.Message {
	mi := &file_shared_err_details_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreconditionFailure_Violation.ProtoReflect.Descriptor instead.
func (*PreconditionFailure_Violation) Descriptor() ([]byte, []int) {
	return file_shared_err_details_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PreconditionFailure_Violation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PreconditionFailure_Violation) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PreconditionFailure_Violation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_shared_err_details_proto protoreflect.FileDescriptor

const file_shared_err_details_proto_rawDesc = "" +
	"\n" +
	"\x18shared/err_details.proto\x12\x06shared\"H\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"O\n" +
	"\n" +
	"BadRequest\x12A\n" +
	"\x10field_violations\x18\x01 \x03(\v2\x16.shared.FieldViolationR\x0ffieldViolations\"\xb9\x01\n" +
	"\x13PreconditionFailure\x12E\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2%.shared.PreconditionFailure.ViolationR\n" +
	"violations\x1a[\n" +
	"\tViolation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB%Z#protobuf/shared/golang/errdetailspbb\x06proto3"

var (
	file_shared_err_details_proto_rawDescOnce sync.Once
	file_shared_err_details_proto_rawDescData []byte
)

func file_shared_err_details_proto_rawDescGZIP() []byte {
	file_shared_err_details_proto_rawDescOnce.Do(func() {
		file_shared_err_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_err_details_proto_rawDesc), len(file_shared_err_details_proto_rawDesc)))
	})
	return file_shared_err_details_proto_rawDescData
}

var file_shared_err_details_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_err_details_proto_goTypes = []any{
	(*FieldViolation)(nil),                // 0: shared.FieldViolation
	(*BadRequest)(nil),                    // 1: shared.BadRequest
	(*PreconditionFailure)(nil),           // 2: shared.PreconditionFailure
	(*PreconditionFailure_Violation)(nil), // 3: shared.PreconditionFailure.Violation
}
var file_shared_err_details_proto_depIdxs = []int32{
	0, // 0: shared.BadRequest.field_violations:type_name -> shared.FieldViolation
	3, // 1: shared.PreconditionFailure.violations:type_name -> shared.PreconditionFailure.Violation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_err_details_proto_init() }
func file_shared_err_details_proto_init() {
	if File_shared_err_details_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_err_details_proto_rawDesc), len(file_shared_err_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_err_details_proto_goTypes,
		DependencyIndexes: file_shared_err_details_proto_depIdxs,
		MessageInfos:      file_shared_err_details_proto_msgTypes,
	}.Build()
	File_shared_err_details_proto = out.File
	file_shared_err_details_proto_goTypes = nil
	file_shared_err_details_proto_depIdxs = nil
}
