name: CI Chat Service

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]
    paths:
      - 'adapter/**'
      - 'app/chatapp/**'
      - 'cmd/chat/**'
      - 'config/**'
      - 'event/**'
      - 'outbox/**'
      - 'pkg/**'
      - 'protobuf/**'
      - 'types/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: test
        run: make chat-test
