// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: manager/proto/user_internal.proto

package userinternalpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	mi := &file_manager_proto_user_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_internal_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LastOnlineAt  *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_online_at,json=lastOnlineAt,proto3" json:"last_online_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_manager_proto_user_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_user_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_user_internal_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfoResponse) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoResponse) GetLastOnlineAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastOnlineAt
	}
	return nil
}

var File_manager_proto_user_internal_proto protoreflect.FileDescriptor

const file_manager_proto_user_internal_proto_rawDesc = "" +
	"\n" +
	"!manager/proto/user_internal.proto\x12\amanager\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x0fUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xed\x01\n" +
	"\x10UserInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12@\n" +
	"\x0elast_online_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\flastOnlineAt2V\n" +
	"\x13UserInternalService\x12?\n" +
	"\bUserInfo\x12\x18.manager.UserInfoRequest\x1a\x19.manager.UserInfoResponseB(Z&protobuf/manager/golang/userinternalpbb\x06proto3"

var (
	file_manager_proto_user_internal_proto_rawDescOnce sync.Once
	file_manager_proto_user_internal_proto_rawDescData []byte
)

func file_manager_proto_user_internal_proto_rawDescGZIP() []byte {
	file_manager_proto_user_internal_proto_rawDescOnce.Do(func() {
		file_manager_proto_user_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_proto_user_internal_proto_rawDesc), len(file_manager_proto_user_internal_proto_rawDesc)))
	})
	return file_manager_proto_user_internal_proto_rawDescData
}

var file_manager_proto_user_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_manager_proto_user_internal_proto_goTypes = []any{
	(*UserInfoRequest)(nil),     // 0: manager.UserInfoRequest
	(*UserInfoResponse)(nil),    // 1: manager.UserInfoResponse
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_manager_proto_user_internal_proto_depIdxs = []int32{
	2, // 0: manager.UserInfoResponse.last_online_at:type_name -> google.protobuf.Timestamp
	0, // 1: manager.UserInternalService.UserInfo:input_type -> manager.UserInfoRequest
	1, // 2: manager.UserInternalService.UserInfo:output_type -> manager.UserInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_manager_proto_user_internal_proto_init() }
func file_manager_proto_user_internal_proto_init() {
	if File_manager_proto_user_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_proto_user_internal_proto_rawDesc), len(file_manager_proto_user_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_proto_user_internal_proto_goTypes,
		DependencyIndexes: file_manager_proto_user_internal_proto_depIdxs,
		MessageInfos:      file_manager_proto_user_internal_proto_msgTypes,
	}.Build()
	File_manager_proto_user_internal_proto = out.File
	file_manager_proto_user_internal_proto_goTypes = nil
	file_manager_proto_user_internal_proto_depIdxs = nil
}
